app2/urls.py
from django.urls import path
from app2.views import *
app_name="app2"
urlpatterns=[
    
    path('yash/',yash,name='yash'),
]

app3/urls.py
from django.urls import path
from app3.views import *
app_name="app3"
urlpatterns=[
    
    path('dilli/',dilli,name='dilli')
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2,app3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('abhi/',abhi,name='abhi'),
    
    path('app2/',include('app2.urls')), 
    
    path('app3/',include('app3.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def abhi(request):
    return render(request,'abhi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.


def yash(request):
    return render(request,'yash.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def dilli(request):
    return render(request,'dilli.html')

templates/abhi.html
<html>
    <title>abhi</title>
<body>
    <center>
        <h1>This is the app1 function</h1>
        <h1>welcome to mr.abhi</h1>

        <h2><a href="{% url 'app2:yash' %}">go to yash page</a></h2>
        <h2><a href="{% url 'app3:dilli' %}">go to dilli page</a></h2>
        


    </center>
</body>
</html>

templates/dilli.html
<html>
    <title>dilli</title>
<body>
    <center>
        <h1>This is the app3 function</h1>
        <h1>welcome to mr.dilli</h1>


        <h2><a href="{% url 'abhi' %}">go to abhi page</a></h2>
        <h2><a href="{% url 'app2:yash' %}">go to yash page</a></h2>
        


    </center>
</body>
</html>

templates/yash.html
<html>
    <title>yash</title>
<body>
    <center>
        <h1>This is the app2 function</h1>
        <h1>welcome to mr.yash</h1>


        <h2><a href="{% url 'abhi' %}">go to abhi page</a></h2>
        <h2><a href="{% url 'app3:dilli' %}">go to dilli page</a></h2>
        


    </center>
</body>
</html>